"""
千绘莉工具箱 (Chieri Toolbox) - B站弹幕转高精 ASS 悬浮字幕引擎 (DanmakuToAss)
将 B站 XML 弹幕流转换为无损 PotPlayer/VLC/手机端均可完美挂载的 .ass 格式外挂字幕。
支持防重叠轨道智能碰撞排版、滚动/顶部/底部弹幕样式解构、十进制 BGR 颜色还原与字体平滑。
"""

import os
import re
import math
import html
import requests
from typing import Optional, List, Tuple, Dict, Any
import xml.etree.ElementTree as ET


def _format_ass_time(seconds: float) -> str:
    """将秒数格式化为 ASS 标准时间戳: H:MM:SS.cs"""
    if seconds < 0:
        seconds = 0.0
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    cs = int(round((seconds - int(seconds)) * 100))
    if cs >= 100:
        cs = 99
    return f"{h}:{m:02d}:{s:02d}.{cs:02d}"


def _dec_color_to_ass(dec_color: int) -> str:
    """将 B站十进制 RGB 颜色 (0~16777215) 转换为 ASS 的 &H00BBGGRR& 格式"""
    try:
        dec = int(dec_color)
    except Exception:
        dec = 16777215
    r = (dec >> 16) & 0xFF
    g = (dec >> 8) & 0xFF
    b = dec & 0xFF
    return f"&H00{b:02X}{g:02X}{r:02X}&"


class DanmakuItem:
    def __init__(
        self,
        time_sec: float,
        mode: int,
        font_size: int,
        color_dec: int,
        text: str
    ):
        self.time_sec = max(0.0, float(time_sec))
        self.mode = int(mode)  # 1,2,3: 滚动, 4: 底部, 5: 顶部
        self.font_size = int(font_size)
        self.color_dec = int(color_dec)
        self.text = text.strip()
        # 预估字符渲染宽度 (以 1080P 下基准字号测算: 汉字宽约等于字号，英文字符宽约 0.55 字号)
        self.char_len = sum(1.0 if ord(c) > 127 else 0.55 for c in self.text)


class DanmakuToAssConverter:
    def __init__(
        self,
        screen_w: int = 1920,
        screen_h: int = 1080,
        roll_duration: float = 8.0,
        font_name: str = "SimHei",
        font_size: int = 38,
        alpha_opacity: float = 0.85
    ):
        self.screen_w = screen_w
        self.screen_h = screen_h
        self.roll_duration = roll_duration
        self.font_name = font_name
        self.font_size = font_size
        self.alpha_opacity = alpha_opacity

    def parse_xml_content(self, xml_text: str) -> List[DanmakuItem]:
        """解析 B站 XML 弹幕数据，健壮防御非法字符与未闭合标签"""
        items: List[DanmakuItem] = []
        # 正则表达式兜底提取，防止不规范字符导致 XML 解析中断
        p_pattern = re.compile(r'<d\s+p="([^"]+)">([^<]*)</d>', re.IGNORECASE)
        for m in p_pattern.finditer(xml_text):
            p_attr = m.group(1).split(",")
            content = html.unescape(m.group(2))
            if len(p_attr) >= 4 and content:
                try:
                    time_sec = float(p_attr[0])
                    mode = int(p_attr[1])
                    fsize = int(p_attr[2])
                    color = int(p_attr[3])
                    items.append(DanmakuItem(time_sec, mode, fsize, color, content))
                except Exception:
                    continue

        items.sort(key=lambda x: x.time_sec)
        return items

    def convert_to_ass(self, xml_text: str, title: str = "Bilibili Danmaku") -> str:
        """核心转换：轨道防重叠排版，生成标准 ASS 文本"""
        danmakus = self.parse_xml_content(xml_text)

        # 构建 ASS 头部
        ass_header = f"""[Script Info]
; Script generated by Chieri Toolbox DanmakuToAss Engine
Title: {title}
ScriptType: v4.00+
Collisions: Normal
PlayResX: {self.screen_w}
PlayResY: {self.screen_h}
Timer: 100.0000
WrapStyle: 2

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Danmaku,{self.font_name},{self.font_size},&H00FFFFFF,&H000000FF,&H00000000,&H90000000,0,0,0,0,100,100,0,0,1,1.5,0,7,20,20,20,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
        dialogue_lines: List[str] = []

        # 轨道分配表: track_idx -> 该轨道当前可用时间戳 (即上一条弹幕离开屏幕边缘的时刻)
        line_height = int(self.font_size * 1.15) + 6
        num_tracks = max(1, (self.screen_h - 100) // line_height)
        roll_track_free_times = [0.0] * num_tracks
        top_track_free_times = [0.0] * (num_tracks // 2)
        bottom_track_free_times = [0.0] * (num_tracks // 2)

        for d in danmakus:
            start_t = d.time_sec
            ass_color = _dec_color_to_ass(d.color_dec)
            approx_px_width = int(d.char_len * self.font_size)

            # 1. 滚动弹幕 (Mode 1, 2, 3)
            if d.mode in (1, 2, 3):
                end_t = start_t + self.roll_duration
                # 寻找最佳不碰撞轨道
                best_track = 0
                min_free_t = roll_track_free_times[0]
                allocated = False

                for t_idx in range(num_tracks):
                    if roll_track_free_times[t_idx] <= start_t:
                        best_track = t_idx
                        allocated = True
                        break
                    if roll_track_free_times[t_idx] < min_free_t:
                        min_free_t = roll_track_free_times[t_idx]
                        best_track = t_idx

                y_pos = 40 + best_track * line_height
                # 弹幕完全离开右侧屏幕的时间
                leave_right_time = start_t + (self.roll_duration * (approx_px_width / float(self.screen_w + approx_px_width)))
                roll_track_free_times[best_track] = max(roll_track_free_times[best_track], leave_right_time + 0.3)

                start_str = _format_ass_time(start_t)
                end_str = _format_ass_time(end_t)
                x_start = self.screen_w + 10
                x_end = -approx_px_width - 10

                line = f"Dialogue: 0,{start_str},{end_str},Danmaku,,0,0,0,,{{\\move({x_start},{y_pos},{x_end},{y_pos})\\c{ass_color}}}{d.text}"
                dialogue_lines.append(line)

            # 2. 顶部固定弹幕 (Mode 5)
            elif d.mode == 5:
                duration_fixed = 4.5
                end_t = start_t + duration_fixed
                best_track = 0
                for t_idx in range(len(top_track_free_times)):
                    if top_track_free_times[t_idx] <= start_t:
                        best_track = t_idx
                        break
                top_track_free_times[best_track] = end_t + 0.2
                y_pos = 40 + best_track * line_height

                start_str = _format_ass_time(start_t)
                end_str = _format_ass_time(end_t)
                x_center = self.screen_w // 2
                line = f"Dialogue: 0,{start_str},{end_str},Danmaku,,0,0,0,,{{\\an8\\pos({x_center},{y_pos})\\c{ass_color}}}{d.text}"
                dialogue_lines.append(line)

            # 3. 底部固定弹幕 (Mode 4)
            elif d.mode == 4:
                duration_fixed = 4.5
                end_t = start_t + duration_fixed
                best_track = 0
                for t_idx in range(len(bottom_track_free_times)):
                    if bottom_track_free_times[t_idx] <= start_t:
                        best_track = t_idx
                        break
                bottom_track_free_times[best_track] = end_t + 0.2
                y_pos = self.screen_h - 40 - best_track * line_height

                start_str = _format_ass_time(start_t)
                end_str = _format_ass_time(end_t)
                x_center = self.screen_w // 2
                line = f"Dialogue: 0,{start_str},{end_str},Danmaku,,0,0,0,,{{\\an2\\pos({x_center},{y_pos})\\c{ass_color}}}{d.text}"
                dialogue_lines.append(line)

        return ass_header + "\n".join(dialogue_lines) + "\n"


def convert_danmaku_xml_file(xml_path: str, ass_path: str, title: str = "") -> Tuple[bool, str]:
    """读取 XML 弹幕文件并转换为 ASS 文件"""
    if not os.path.isfile(xml_path):
        return False, f"XML 弹幕文件不存在: {xml_path}"
    try:
        with open(xml_path, "r", encoding="utf-8", errors="replace") as f:
            content = f.read()
        converter = DanmakuToAssConverter()
        ass_content = converter.convert_to_ass(content, title or os.path.basename(xml_path))
        os.makedirs(os.path.dirname(os.path.abspath(ass_path)), exist_ok=True)
        with open(ass_path, "w", encoding="utf-8-sig") as f:
            f.write(ass_content)
        return True, ass_path
    except Exception as e:
        return False, f"转换 ASS 字幕异常: {e}"


def fetch_bilibili_danmaku_xml(cid: int or str, sessdata: str = "") -> Optional[str]:
    """根据 B站视频 cid 实时拉取最新全量弹幕 XML"""
    url = f"https://comment.bilibili.com/{cid}.xml"
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) ChieriToolbox/2.1",
        "Referer": "https://www.bilibili.com"
    }
    if sessdata:
        headers["Cookie"] = f"SESSDATA={sessdata}"
    try:
        resp = requests.get(url, headers=headers, timeout=12)
        if resp.status_code == 200:
            resp.encoding = "utf-8"
            return resp.text
    except Exception as e:
        print(f"[DanmakuToAss] 拉取弹幕失败 (cid={cid}): {e}")
    return None


# 兼容别名
DanmakuConverter = DanmakuToAssConverter
convert_danmaku_xml_to_ass = convert_danmaku_xml_file

